on:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC

name: build-nightly

jobs:
  tests:
    name: PHP ${{ matrix.php }}-${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest

        php:
          - 8.0
          - 8.1

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup nightly PHP
        uses: shivammathur/setup-php@2.14.0
        with:
          php-version: '8.1'
          extensions: mbstring
          ini-values: post_max_size=256M, max_execution_time=180
          tools: composer:v2

      - name: Update composer
        run: composer self-update

      - name: Install dependencies with composer
        run: composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi --ignore-platform-reqs

      - name: Run tests with codeception
        run: |
          php -S 127.0.0.1:8080 -t tests/_data/public > tests/_data/runtime/yii.log 2>&1 &
          vendor/bin/codecept run
